apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-frances-deployment
  labels:
    app: restaurante-frances
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-frances
  template:
    metadata:
      labels:
        app: restaurante-frances
    spec:
      containers:
      - name: restaurante-frances
        image: thezyon/restaurante-frances:latest
        ports:
        - containerPort: 80
        # se seu app usa outra porta, ajuste aqui
        env:
        - name: PORT
          value: "80"

